### ISSUE TITLE
Results file 

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#169]
The file doesn't open at the end of the experiment and the given values (mean of last n reversals) are not correct. I've included an STM experiment ('detect the rippled stimulus') to replicate the problems. 
[STM_2AFC_4cpo_20170217.zip](https://github.com/exporl/apex3/files/783445/STM_2AFC_4cpo_20170217.zip)

@AlexanderDudek

**Comment by AlexanderDudek** [comment]
The file doesn't open properly at the end because of wrong \<resultparameters> in \<results> in the apx file
- Never use spaces in a parameter name, eg: _\<parameter name="reversals for mean">6\</parameter>_
- - Instead, use the following format: _\<parameter name="line_reversalsformean">6\</parameter>_ 
- - - "line_" refers to the linegraph used for adaptive procedures
- - - the default value is actually 6 so this is not needed

- The parameter modulation_depth shouldn't be needed in resultparameters - is there a specific reason why it's in here?

- resultsparameters don't have any relation with fixed- or variableparameters, their purpose is to configure the calculations/algorithms of the resultsviewer or to pass experiment-specific values on to custom RV code
-> **Specific config params will be added in the manual**

- There is a bug in the textual representation of the mean, where the total amount of reversals or trials was used instead of the default amount (6) or the configured amount (line_reversalsformean & line_trialsformean) 
-> **FIXED**

- There is a bug in the storage of the mean, where the std is shown instead 
-> **FIXED**

This will be included in the next update of Apex, for now please replace ../apex/data/resultsviewer/resultsviewer.js with the included file:
[resultsviewer.zip](https://github.com/exporl/apex3/files/790774/resultsviewer.zip)

**Comment by SaraMagits** [comment]
In 'foneemidentificatie' the confusion matrix is not shown correctly on the screen. The last column 'put' is not visible. I've attached an apr-file as an example of the problem. 
[Demo_vowel10afc-results_test2.zip](https://github.com/exporl/apex3/files/932459/Demo_vowel10afc-results_test2.zip)
