### ISSUE TITLE
windows error program has stopped working (LISTEN)

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex3#179]
APEX stops working while going through the experiment at seemingly random moments (10/10). I've sent an e-mail to Sanne with an example experiment.

**Comment by Gundersanne** [comment]
There's an assert that fails line 68 procedureapiimplementation.cpp

if I add default answer element like so:
`<screen id="confirmation_screen">
<default_answer_element>buttongroup1</default_answer_element>
</screen>`

it works. Try this?

**Comment by SaraMagits** [comment]
It still gives the same error on my computer, even when I add the default answer element in confirmation screen.

**Comment by Gundersanne** [comment]
Right, I was testing the wrong experiment.

There's a SIGFPE because of a modulo 0. See src/lib/apextools/random.cpp:71 called from trialdata.cpp:71.

`mRandom.nextUInt(((int)m_stimuli.size()) ); // stimulus number to be used`

if m_stimuli.size() is 0, a % 0 gets executed and thus SIFPE.

We should really check that n != 0 in apextools/random.cpp. Or just let it use the common implementation.

Thank you Sara :)

**Comment by Gundersanne** [comment]
Also why is m_stimuli.size() 0 in the first place ?

**Comment by Gundersanne** [comment]
@SaraMagits  I found the issue. 

`      <trial id="confirmation_trial">
        <screen id="confirmation_screen"/>
      </trial>
`
And it selects a random trial. Then it tries to select this one and it fails because it has no stimuli associated with it.

So you can just delete those lines.

We should probably have some sort of validation for this though.

**Comment by SaraMagits** [comment]
Now it works, thank you!
